---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pugst-cinema
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pugst-cinema
  template:
    metadata:
      labels:
        app: pugst-cinema
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: homelab-configs
              mountPath: /usr/share/nginx/html
              subPath: pugst-cinema/src
            - name: audio-files
              mountPath: /usr/share/nginx/html/audio
      volumes:
        - name: homelab-configs
          persistentVolumeClaim:
            claimName: homelab-configs-pvc
        - name: audio-files
          hostPath:
            path: /hdd/workspace/pugst-cinema
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: pugst-cinema
  namespace: homelab
spec:
  selector:
    app: pugst-cinema
  ports:
    - port: 8001
      targetPort: 80
  type: LoadBalancer 
