emulatorjs:
  cache_limit: null
  controls: {}
  debug: false
  disable_auto_unload: false
  disable_batch_bootup: false
  netplay:
    enabled: false
    ice_servers: []
  settings: {}
exclude:
  platforms:
  - .database
  - .resources
  roms:
    multi_file:
      names:
      - .psx
      - .dreamcast
      - .ps2
      - .saturn
      parts:
        extensions: []
        names: []
    single_file:
      extensions: []
      names:
      - .psx
      - .dreamcast
      - .ps2
      - .saturn
filesystem:
  firmware_folder: bios
  roms_folder: roms
scan:
  media:
    - box3d
    - miximage
    - physical
    - screenshot
    - marquee
    - manual
    - video
    - title_screen
  priority:
    artwork:
    - ss
    - hltb
    language:
    - en
    metadata:
    - ss
    - hltb
    region:
    - us
    - wor
    - ss
    - eu
    - jp
system:
  platforms: {}
  versions: {}
