apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    namespace: homelab
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZDU5dGRqMU9td2U4c2NF
            d0ladTdwT1ZERWVVdkliWDFCc3dFajU0WTJnCmdpbWNROGZnajJuMmY3WDVJSGs3
            N25wcmdMREJUN3pNdGY0Q20wbU1xdjQKLS0tIFovREJscFptUGdPYW45ZlIwQzhh
            N0NNTVFtOFluR2t2WFl6S21nWkFaK0kKsmsXmxuJiWISTXNegi0DVil3QFLgqSVm
            tZDpz8YMzv5UybrnRNbHCLITFycvwbNyeGw858l4nqgEpap0wX7PLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T19:53:26Z"
    mac: ENC[AES256_GCM,data:ZltQMTH4/mCXkYdvBFOY9tXMJ+VF2bUduOlSLeVpG2GembPlISRP9PT5gtF7ed2vQ5VMdyeLdPxxZuMTGNnUZiJ2CjeSpx3lKbBt7v9TnT1Da4GIWCFH4li+0kHuJJ7RXQ2uLDGCqisIaj/wi02JkYSaG6YGhzR70EqTmjPw3o0=,iv:McR8k+DUhFSeLYaPaK1F3w0/9GnZ5QjM31mcQhro0Nc=,tag:5GzKiEEnVyZ3HEZybV6Vcw==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homelab
stringData:
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:sHzNJF6lVBQdOnUfGY3BvBwfznSoWvx1dg==,iv:IgWQysajWhpOo1sOaAPqnDA6H72F66zUbwt+TT5JxbQ=,tag:0UEa5QXYP894Zro41aai7Q==,type:str]
    HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:ipfLyESLPXDb67XLR03zf8SdgpA=,iv:LEPsAgHD/Ubm/BSIY2/+5B91Q0PlxaCUZHorIkGLVv0=,tag:yCSL+zeWai+FxeXKsrGp+Q==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_URL: ENC[AES256_GCM,data:ZIfaQObRBkhQbEOMOKiVAhmVmB0w9wDh,iv:SmvwQYQ6piSMSzkCBhei2uDULdxc8JAcI25zo+aDBiI=,tag:gA2WqCxqunydJ3odw5YsEw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:f4GI,iv:r6E6t0Zvib8/O4CxaX/2+R8GptQvSdk5DFpi4ArUMK8=,tag:6DXDGH0fKqmTeMlwkU/6ng==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:2gPsSMjS+jhs,iv:kHiXhn4avmurTbpa6s1o0Zufy+AUuse4EOAx1VAOxmg=,tag:9YaOyGesCRh+Ov+rWV8oNQ==,type:str]
    HOMEPAGE_VAR_FILEBROWSER_URL: ENC[AES256_GCM,data:3OrPJ4u9VTVyS2hVW2HP7tTn7Ro3mUDtyCEMhOUXgu1T,iv:DePF84fJk1Q7FbEuYeR367/j7NgMIoa932Wp7zlynF8=,tag:yOXwxypSX40/AvhuW1r0ow==,type:str]
    HOMEPAGE_VAR_METUBE_URL: ENC[AES256_GCM,data:M3r1U+F0aRj4ePKx/OEUnXIRj/aOQdpiSQ==,iv:66fpyAELnhMlB1PQ3Ar01nGLl6F2ZBnrBXoOZcHXoLs=,tag:XcoDdBZmGDiM+0e0C1mshg==,type:str]
    HOMEPAGE_VAR_LOST_URL: ENC[AES256_GCM,data:FMUBT/mFhNjoYMNai2/L2Gjbs6wwQlfpo3YALV95qfA=,iv:zFMtTXdHT6YniMNH/jYIPgOkPa6HrCWWB/ctgnNNjns=,tag:q5qCaDGiUBn91xu3cD3x9g==,type:str]
    HOMEPAGE_VAR_CINEMA_URL: ENC[AES256_GCM,data:EWOr9cZA4BAC8Q1Q6csFhxpo+YZzh+073aJ9ft1MxMOOew==,iv:QRwGO3Cb2ay2HZFcQuX00YbGOFKOgxNeQ2aVXRBdis8=,tag:ylmD9xpRhtlW5et3O8XZZA==,type:str]
    HOMEPAGE_VAR_PHOTOPRISIM_URL: ENC[AES256_GCM,data:2B5SUNhAj1vmd3ihtJoVNWDF3P1ekwuayWoZ9ETa7mDZiA==,iv:kl7iO8oik1C9kU5tYmw5DB/OztXjoCrNk8kqHJ5qcxU=,tag:aTYomluq5arV7eAGfOoAVw==,type:str]
    HOMEPAGE_VAR_PHOTOPRISIM_TOKEN: ENC[AES256_GCM,data:4M0Ky3DRz7yviU4X7Jo5O0fkZ9C1AXzEiJLI,iv:/M42j8/G2zExe+ZXEsEKlWxCVLvdN4hpgYqE0+NsGtE=,tag:LRU5tP1fipsuLHQBQHzPXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmZDU5dGRqMU9td2U4c2NF
            d0ladTdwT1ZERWVVdkliWDFCc3dFajU0WTJnCmdpbWNROGZnajJuMmY3WDVJSGs3
            N25wcmdMREJUN3pNdGY0Q20wbU1xdjQKLS0tIFovREJscFptUGdPYW45ZlIwQzhh
            N0NNTVFtOFluR2t2WFl6S21nWkFaK0kKsmsXmxuJiWISTXNegi0DVil3QFLgqSVm
            tZDpz8YMzv5UybrnRNbHCLITFycvwbNyeGw858l4nqgEpap0wX7PLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T19:53:26Z"
    mac: ENC[AES256_GCM,data:ZltQMTH4/mCXkYdvBFOY9tXMJ+VF2bUduOlSLeVpG2GembPlISRP9PT5gtF7ed2vQ5VMdyeLdPxxZuMTGNnUZiJ2CjeSpx3lKbBt7v9TnT1Da4GIWCFH4li+0kHuJJ7RXQ2uLDGCqisIaj/wi02JkYSaG6YGhzR70EqTmjPw3o0=,iv:McR8k+DUhFSeLYaPaK1F3w0/9GnZ5QjM31mcQhro0Nc=,tag:5GzKiEEnVyZ3HEZybV6Vcw==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
