apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  configManagementPlugins: |
    - name: ksops
      generate:
        command: ["sh", "-c"]
        args: ["kustomize build --enable-alpha-plugins --enable-exec ."]
