apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
  namespace: argocd
spec:
  template:
    spec:
      volumes:
        - name: custom-tools
          emptyDir: {}
        - name: sops-age-keys
          secret:
            secretName: sops-age-key
        - name: cmp-plugins
          emptyDir: {}
        - name: ksops-plugin
          configMap:
            name: ksops-plugin
        - name: cmp-server-bin
          emptyDir: {}

      initContainers:
        - name: install-ksops
          image: viaductoss/ksops:v4.3.1
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Installing KSOPS and Kustomize" && \
              cp /usr/local/bin/ksops /custom-tools/ksops && \
              cp /usr/local/bin/kustomize /custom-tools/kustomize
          volumeMounts:
            - mountPath: /custom-tools
              name: custom-tools

        - name: copyutil
          image: quay.io/argoproj/argocd:v3.1.8
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Copying argocd-cmp-server binary..." && \
              cp /usr/local/bin/argocd-cmp-server /var/run/argocd/argocd-cmp-server && \
              chmod +x /var/run/argocd/argocd-cmp-server
          volumeMounts:
            - mountPath: /var/run/argocd
              name: cmp-server-bin

      containers:
        - name: argocd-repo-server
          volumeMounts:
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /sops-age-keys
              name: sops-age-keys
              readOnly: true
            - name: cmp-plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: ksops-plugin
              subPath: plugin.yaml
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
            - mountPath: /var/run/argocd
              name: cmp-server-bin
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age-keys/age.agekey
            - name: XDG_CONFIG_HOME
              value: /.config
            - name: KUSTOMIZE_PLUGIN_HOME
              value: /.config/kustomize/plugin

        - name: argocd-cmp-server
          image: quay.io/argoproj/argocd:v3.1.8
          command: ["/var/run/argocd/argocd-cmp-server"]
          volumeMounts:
            - mountPath: /var/run/argocd
              name: cmp-server-bin
            - name: cmp-plugins
              mountPath: /home/argocd/cmp-server/plugins
            - name: ksops-plugin
              subPath: plugin.yaml
              mountPath: /home/argocd/cmp-server/config/plugin.yaml
            - mountPath: /usr/local/bin/kustomize
              name: custom-tools
              subPath: kustomize
            - mountPath: /usr/local/bin/ksops
              name: custom-tools
              subPath: ksops
            - mountPath: /sops-age-keys
              name: sops-age-keys
              readOnly: true
          env:
            - name: SOPS_AGE_KEY_FILE
              value: /sops-age-keys/age.agekey
