---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metube
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metube
  template:
    metadata:
      labels:
        app: metube
    spec:
      containers:
        - name: metube
          image: ghcr.io/alexta69/metube
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: downloads
              mountPath: /downloads
            - name: hdd-data
              mountPath: /hdd
      volumes:
        - name: downloads
          hostPath:
            path: /hdd/media/music/.tmp/youtube
            type: Directory
        - name: hdd-data
          hostPath:
            path: /hdd
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: metube
  namespace: homelab
spec:
  selector:
    app: metube
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 32081
  type: NodePort
