directories:
  incomplete: /var/slskd/incomplete
  downloads: /var/slskd/downloading

shares:
  directories:
    - /var/slskd/shared
  filters:
    - \.ini$
    - Thumbs.db$
    - \.DS_Store$
  cache:
    storage_mode: memory
    workers: 16
    retention: ~
