---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nicotine
  namespace: homelab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nicotine
  template:
    metadata:
      labels:
        app: nicotine
    spec:
      containers:
        - name: nicotine
          image: hockeygoalie35/nicotine-novnc-rpi:arm64
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
          ports:
            - containerPort: 6080
          volumeMounts:
            - name: data
              mountPath: /data
            - name: music-shares
              mountPath: /data/shares
            - name: music-tmp
              mountPath: /data/.local/share/nicotine/downloads
              subPath: downloads
            - name: music-tmp
              mountPath: /data/.local/share/nicotine/incomplete
              subPath: incomplete
            - name: music-tmp
              mountPath: /data/.local/share/nicotine/received
              subPath: received
      volumes:
        - name: data
          hostPath:
            path: /home/pi/Appdata/nicotine/data
            type: DirectoryOrCreate
        - name: music-shares
          hostPath:
            path: /hdd/media/music
            type: Directory
        - name: music-tmp
          hostPath:
            path: /hdd/media/music/.tmp
            type: Directory
---
apiVersion: v1
kind: Service
metadata:
  name: nicotine
  namespace: homelab
spec:
  selector:
    app: nicotine
  ports:
    - port: 6080
      targetPort: 6080
  type: LoadBalancer
