---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-token
  namespace: homelab
spec:
  encryptedData:
    token: AgAsTv3IuBt8Viso1wSRIIqf/48i2clPUExKfrUymwy5iXMZwdu+Ur6tHVYl3i+3mSlmW08dh9ZyJ4E6O/oj21E1UkDuaSn+yaqRoVRaPDZWcgpcWXyTrtjj2Oc+TW4YNsIeRp0ZM9aevlRT98/HQprZG2YUAb6OB9Dn8PUsSuz/bZNKm8FicMbi6EzKiq7JAFYjTY9PtY25Fm8Zb527WESfazh5sZh8Jpj4CuQn44/MpH10j4Z/IlNZGUkSsg70vTLLmue12kaAL3pEctcndtj/AkNugYczPZnBdJ/yJt74ZtQP+59FQQvHHOV9hSp5+LHkorG9yH5K6Uvuo4ojfAJRcsv/J0WklSIG7oqBpVFzDPPt5LPtFG0Cy0xfAU4d5j2EIQ3SqjkcR+jfsn74ZRAab3l084ngYRlmO5gJMeo3ye+UhRGC2k7Pm0c9TpMAVlhySE5cNQJ2Ewu5vC5RQzEUq4UgdNkNbbSzBcfouX6i1xwilsz3XPAn5EfepIMyHSB+mopvTYP1O/BM9lsCGvXNYMVxmcgET6+HQEyCinj0E3S0HxwUjGdMev1zNIfAh7muML12Qr/l6ZQCRymu/aNXIBmJ0gVYqoIKl3k80LNZfA3efjw/QzLej9QkbQyvzpNgGiIhJYyJDiz1u7MTKrdaxSwit/IQSJHulwh3L4chlo2MmA2pKNllYD+6HZ18jzrhYEnWJgfkX5amPuO5gCo67peOsdLH4LQjhFRWaILOIhtiydkd/2KBCcbuILdKuUSank1hY0ydZXiUYXv3FYp0C2AP4FMEaR6xsOgZQpEYzmmkHIeVKlvdSKPCWMsbyGUe2figMzwNwmFtZPmlfVDSNs0D+VfoIXKvxKWxVTcvtd4B4gpMkPwipw3Lh7Od8jg/unPo1VSZqlp4d3yWlEJ2XtHQarfiYk74eL63wzZBBR/9iBKlVw/p
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-token
      namespace: homelab
    type: Opaque
