apiVersion: v1
kind: Secret
metadata:
    name: tunnel-token
    namespace: homelab
type: Opaque
stringData:
    token: ENC[AES256_GCM,data:1EYAX2HWwpApKJcNUPZVnoMf0zAcbMu55arrn3Duw5ik5PC06NzguEMypfq5c5G7CUviTVJ709d8F1bZcFAUhowGyYJemIQGpd3SshSCb9QDj/ZFmZv/0IVUJ/oLnbm/ju+hwYWHVa4CGrMezg6PZOQ6oZsJDaySsPrhFCnH8ZpxuFLawQ7csrJbcK1egTi8Kl7xXq45HbawM/HreGQg0Hs8bkw48f0BILmX5qT3F4QMNtH71ys8Fg==,iv:Gm/TeN8VjFMVsfENvRGsYvwdUoY9O42awpbf2ec/Vys=,tag:POhQyXPXbwk69uLLZcZrlQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQcXJJdVA2VlhEQ1haZ0tQ
            MWdUUVBmbzVPQ0p3ZnY3OTdVUjg4eGhhcUhZCmFDNDVQZFdkc3hScWdmWCtkbjE0
            ZTV2S1dRajFKZ1d0eURYUG5iTFcvQjQKLS0tIE51MjQ5RUlZREdYL25IY2NZUU9N
            eVl0VVZoM1ZuYUNHbmtKR2tKSFlCWUUKI0DeDNbubxM763k1dY61cppm6H2+hrCG
            ZA3XK3YMUNkvQSMVZc8mBP5jGM9QyjCVc8+TRLY53vo3agbPa65gsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T19:53:41Z"
    mac: ENC[AES256_GCM,data:eYKy8gx6giST+s/lL2Ut3B0ZHAtS+oWdt4o1sL3O38ItSLlJfI2aZT7dW1eSqG9+P3QAskrrpFf3L657bmU2SiRIVdRNSHoPwWZsGdCfJyzNLYW+nwL+r3EDVOXRX7PqG2CYSEsqEhWVMjCySaCRv0wYR5azxvBsyuaRznjagBs=,iv:llXl/8T4nUpsmsTwZgHR3y2KZ95YGxWSoslK+tOIohk=,tag:9cRTnnsFeyHa0oph7DVQ8Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
