- Services:
  - Media:
      - Plex:
          href: 'https://app.plex.tv/desktop/'
          description: Plex Media Server
          icon: /icons/plex.png
          siteMonitor: '{{HOMEPAGE_VAR_PLEX_URL}}'
          widget:
            type: plex
            key: '{{HOMEPAGE_VAR_PLEX_API_TOKEN}}'
            url: '{{HOMEPAGE_VAR_PLEX_URL}}'
      - PhotoPrism:
          href: '{{HOMEPAGE_VAR_PHOTOPRISM_URL}}'
          description: Image Gallery
          icon: /icons/photoprism.svg
          siteMonitor: '{{HOMEPAGE_VAR_PHOTOPRISM_URL}}'
          widget:
            type: photoprism
            url: '{{HOMEPAGE_VAR_PHOTOPRISM_URL}}'
            key: '{{HOMEPAGE_VAR_PHOTOPRISM_TOKEN}}'
      - Romm:
          href: '{{HOMEPAGE_VAR_ROMM_URL}}'
          description: Emulator and Rom Manager
          siteMonitor: '{{HOMEPAGE_VAR_ROMM_URL}}'
          icon: /icons/romm.png
          widget:
            type: romm
            url: '{{HOMEPAGE_VAR_ROMM_URL}}'
            fields: ["platforms", "totalRoms", "saves"]
  - Files and Documents:
      - File Browser:
          href: '{{HOMEPAGE_VAR_FILEBROWSER_URL}}'
          description: File server and browser
          icon: /icons/fb.svg
          siteMonitor: '{{HOMEPAGE_VAR_FILEBROWSER_URL}}'
      - qBittorrent:
          href: '{{HOMEPAGE_VAR_QBITTORRENT_URL}}'
          description: Torrent Manager
          icon: /icons/qbt.png
          siteMonitor: '{{HOMEPAGE_VAR_QBITTORRENT_URL}}'
          widget:
            type: qbittorrent
            url: '{{HOMEPAGE_VAR_QBITTORRENT_URL}}'
            username: '{{HOMEPAGE_VAR_QBITTORRENT_USERNAME}}'
            password: '{{HOMEPAGE_VAR_QBITTORRENT_PASSWORD}}'
      - Metube:
          href: '{{HOMEPAGE_VAR_METUBE_URL}}'
          description: Youtube Downloader
          icon: /icons/metube.png
          siteMonitor: '{{HOMEPAGE_VAR_METUBE_URL}}'
  - Websites:
      - Hurley's Ranch:
          href: '{{HOMEPAGE_VAR_LOST_URL}}'
          description: Lost Website
          icon: /icons/hurl.png
          siteMonitor: '{{HOMEPAGE_VAR_LOST_URL}}'
      - Pugstreet Cinema:
          href: '{{HOMEPAGE_VAR_CINEMA_URL}}'
          description: Movie Podcast
          icon: /icons/favicon.ico
          siteMonitor: '{{HOMEPAGE_VAR_CINEMA_URL}}'
- Admin:
  - ArgoCD:
      href: '{{HOMEPAGE_VAR_ARGOCD_URL}}'
      icon: /icons/argocd.png
      description: Deployment Manager
      siteMonitor: https://192.168.1.99:8090
      widget:
        type: argocd
        url: https://192.168.1.99:8090
        key: '{{HOMEPAGE_VAR_ARGOCD_TOKEN}}'
  - Grafana:
      href: '{{HOMEPAGE_VAR_GRAFANA_URL}}'
      icon: /icons/grafana.svg
      description: Observability Dashboard
      siteMonitor: '{{HOMEPAGE_VAR_GRAFANA_URL}}'
      widget:
        type: grafana
        url: 'http://192.168.1.99:3001'
        username: '{{HOMEPAGE_VAR_GRAFANA_USERNAME}}'
        password: '{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}'
