---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/widgets

- greeting:
    text_size: xl
    text: Welcome to Dungeonware

- resources:
    cpu: true
    memory: true
    uptime: true
    disk: 
         - /
         - /hdd

- search:
    provider: duckduckgo
