---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wrtag-secret
  namespace: homelab
spec:
  encryptedData:
    WRTAG_WEB_API_KEY: AgCgemdgihERcHapB8SYWw8G+Kh65w0YSJQNPAViBCaw7ikwKqTQaV33887bDI4Cw7hvK4oQiuuIO64Fujp954GUDHBvmcYum13G9UW9x0AQD+9E11u4Gm7CIL0TiIT8Op4YuprgeKWDaPy7EZUbK6k7ZNZzuZsDMtx9Na2ovm6cbVAAaooQix2zF4uRAs8MTjNrSkfkYL8eyArnElSIW09LhsJrLa5WGrw4JolIYKTByum+rgt573YrPuZe4o1wWyvr1RZxOWNKApnzuVkLcgD88v3PeJJBwMxhmUnbt+CR6gdtBR1FHdUOpPCQORU0q8qTJSXJRopVoMRiWK6IsZw6gB9aOqnUmCZYlhtbrUD0QMahTlzOq3EVkxOZDG28BGWUPhhcjSZeqW1Nxgk2FSXDkyLAHgkjPN2bFNw+u/Z0HZyTWqYUfWpLDgfs0spoXDsbEBpTF2kG3TxjVjwTmclz10idGg8oR7Ib0U5GM1TUVuU4z5/iJPlIa5BjpATIy8R+5v1A9NK7VKYOEpVRV7dlTSqRP3kHBndVM1uH7DVX1l1wWm2EcYO2TfUlha8hEX2WYmWppVFNeRCOjrBIZ3zDWX1qv9Nv9g/9U5Ntm8hJqYSsH54xeHlaZxgM/0oXOf6mlCMdT3ohSlK2ObgMXbi6pmZeqcNI/2F7u9ANyfunK/mtVFiYV1eloz9MymfQoTXXRrf5D9GpndTxmKmC07CqQZ3K/+IjydFzpJChVipxv44OsEGQc/B00FR8IXtR31QUx5ahYYY1FtVKy3BWL9r6
  template:
    metadata:
      name: wrtag-secret
      namespace: homelab
    type: Opaque
