---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: wrtag-secret
  namespace: homelab
spec:
  encryptedData:
    WRTAG_WEB_API_KEY: AgAV90hObGcu+HWfEJB+/Q/+fRdzVcFumfHCRpM2ZUEnFy9xO3xYmp12Sm3OgeFcgB1/oqDnvgmnESCUwsmUK5HehF/jAru5HuJLr9k1fTihpuP5IoC+C4oDAoLQ7ojJ95ENqIVFdI7XLmbzpsTu3iO8hLA3xs3BzZ1w/2jTmVJxqpXMdElAg1BDaw+6wYxVG74D+DIZwKCWevWyWdIuGwTvyHNN7K+I8ZAsGEpUJ51dQ1SJOgsnLZV8QMdPRgppR19H38WBJoPDtXWHszD7aJ+p/3FhEskNd12DnSkLtigdhMMYL9Zf4kBg2Gc2r/mEX44quKNpCqQfIbD8JMDNTu5YmE6yNWd6/3/ah3FsLuDbGueTGhsFXAWa/YmNflU2ZC65Rgp2WeugelPjplmvj+/hDio3wvcJTFrKTGfC+ZHJlQGUDhHI4CrPL8l7nKx/e/0adjVAHFneuCkAn3A4G2wi+ZeKEZuuao0HHA1yA7lI+V5lAjwKTyCb5SE6SD2QRG3XTlTINXtpuXGuEFXbAA0CyifkR2TBaT+bx4WfwU5cNc4bQHea/TCobdhHLkFgppmF89Vhi/4IZu45LRUcfBAVXJcB4R4SRsKkV7z4yzvNaLjJ6NUgLFK7n+HQEHSkkv2XcjXnuqmBR4UGQeDx/XdQndIRIQVBlbZBT215ahoyT3iJMEj4bye6KmYmh77iDF1wQItBalcpLnJ7eGGSQKwfHAGG4RSy2Hoe/yTWNudAtogA8kDJbaiAeK5v3HHTpyHk+WYryU+oFKsJl76W9yQH
  template:
    metadata:
      name: wrtag-secret
      namespace: homelab
    type: Opaque
