apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    namespace: homelab
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQk5DRjl5dGVhQXVyc3FC
            NWFZalRTMnBVcGlzWDJDWTFHL0ZycXdvMFRRCnhMWFRGNHllSkh3UGtzcHlrdUFs
            S1RpbFhBb01SdjNuWnFNL082eE9jMDgKLS0tIDJuSFl4ZXBSdHM2R3g5aVNuK1RE
            NFdLTE1uRkV6UFY3UFJYTG95eVZvd3MKWu4aYjexh2SZkD2crmkcJ0X4GlGfmiaW
            Mc6e4e//6HoZXTTZ3ip+3cik75Iyh2MpLdZN8W02K2RvchNcsBYvgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T14:48:42Z"
    mac: ENC[AES256_GCM,data:93uRoqRqhrwO+ed/y8OWldyNPYhBMbJVYgrBZtSIgqMycCvtwkDLYOvdNH92rK3VyL3sFDu8V/cOetN/lPoUVdaLQPdAV7qanq9zzPDU6sE/+3AJyiH7xfok76DjlzTnrcVsPLv8rZsLgdS0z2qy02OjAdLs8sZV6gfjAcOHYMc=,iv:vFxCkK/ptSe1HNjK2Wcg7oN8bpw8tR8c6JiVzfzZRtg=,tag:TaKL8/qojwT+cd625Nof0Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homelab
stringData:
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:uYVHvVNWxAe+NlXd78KGK1l6F1axR4zDtQ==,iv:VjAH2FzhWU+XgVuohV+mzG2JPKaSSHCpMFEqQ4mLPV0=,tag:m5mA6tF+ax69AVdOQCZAHQ==,type:str]
    HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:j87Y0eobuyvppcWigVQfIXRaxXY=,iv:hdPNnNjWPWZiN6Nn6fQ9tpJce9vr3pzrXE+V/oVJ2K0=,tag:AeCMdvo2Wwx7k2nvGP6RFw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_URL: ENC[AES256_GCM,data:S1U4gr/9LwfMsq0jNOHI0GEBNnGZm7DN,iv:Y4b+ai8rO+T+RonuiEy3tWc3e2UFX6jmQT9Z2j5e/vg=,tag:ToKGn8SLue1O1+bnsJ26rA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:f4h1,iv:vFUkpaG7D+GvL43VDUFhXxuRkrHYI7wCZBOI0Cu60V4=,tag:ncukya9BkjqnrjkmiS29yw==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:W40SlccJNz1H,iv:ZRdiOzP8p7v4McBElFZb9x4G7i6+N19pvBFPbgPWjKc=,tag:bCwEsQhX7uXuiKaR70nUZA==,type:str]
    HOMEPAGE_VAR_FILEBROWSER_URL: ENC[AES256_GCM,data:yYWZj7XUIjsXcLB/0AmKFaHzDkX/8AceXJaeTL3GS8/C,iv:98CPKnD0+wXc51otCsosEFbNxHVtPGXF9Hyi0y+75/g=,tag:YhXdEgBpkDN/fPlofk2nXg==,type:str]
    HOMEPAGE_VAR_METUBE_URL: ENC[AES256_GCM,data:RI01QoyrICQ79rnSftmUs98dD7llHM10Xw==,iv:ykoQTLPtUQGzYE1DeNVrs1B75mK9D4G6TnmwVKxhXfE=,tag:B44tQMt/wyLEG26JoZA2+Q==,type:str]
    HOMEPAGE_VAR_LOST_URL: ENC[AES256_GCM,data:V6zANJ3QpFSQpea+WK50ikBpOUxtaSpDiLT9q62Y3Pg=,iv:XGJ4GcrTK3uVZhIf4XStU9hp6+Coij4VcwQ39BRGDLc=,tag:mTwzGmg9fxy0siivuz44tg==,type:str]
    HOMEPAGE_VAR_CINEMA_URL: ENC[AES256_GCM,data:uhrFviOSKw7HbGuPL+8b1CK0xh8ntv/yfZhrSpef+/1LVw==,iv:7B9SSZZbX2oBZepXHrtJ/wXcXGP3U48J3zym/Rkbhqs=,tag:HqCIMh9wQnug092IAsYnxQ==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_URL: ENC[AES256_GCM,data:zNug0bMgnYgWOw7kQKsVmJ4SnYzwUR75Y4aoL7lY9aU/YQ==,iv:UIlMjvJvjR+GUws14sk4nTJU6FvNVJTVagohPGeYpDA=,tag:R+iftKWgZPF9mdhxuAx3zA==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_TOKEN: ENC[AES256_GCM,data:qrSel8091tgNz+UH/BIZYfy3rgcwSjQ2MyoK,iv:R96Hq0sxLvWdaB71IQRe2w7xT19kPugMiYTDBHwf44U=,tag:P7BKJKJb+NmK3kxcjvNlfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQk5DRjl5dGVhQXVyc3FC
            NWFZalRTMnBVcGlzWDJDWTFHL0ZycXdvMFRRCnhMWFRGNHllSkh3UGtzcHlrdUFs
            S1RpbFhBb01SdjNuWnFNL082eE9jMDgKLS0tIDJuSFl4ZXBSdHM2R3g5aVNuK1RE
            NFdLTE1uRkV6UFY3UFJYTG95eVZvd3MKWu4aYjexh2SZkD2crmkcJ0X4GlGfmiaW
            Mc6e4e//6HoZXTTZ3ip+3cik75Iyh2MpLdZN8W02K2RvchNcsBYvgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-30T14:48:42Z"
    mac: ENC[AES256_GCM,data:93uRoqRqhrwO+ed/y8OWldyNPYhBMbJVYgrBZtSIgqMycCvtwkDLYOvdNH92rK3VyL3sFDu8V/cOetN/lPoUVdaLQPdAV7qanq9zzPDU6sE/+3AJyiH7xfok76DjlzTnrcVsPLv8rZsLgdS0z2qy02OjAdLs8sZV6gfjAcOHYMc=,iv:vFxCkK/ptSe1HNjK2Wcg7oN8bpw8tR8c6JiVzfzZRtg=,tag:TaKL8/qojwT+cd625Nof0Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
