apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
    name: homepage
    namespace: homelab
    labels:
        app.kubernetes.io/name: homepage
    annotations:
        kubernetes.io/service-account.name: homepage
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYmJEbTN1Qk9kYTliQ1Zo
            NjRIS3hhckdMcTgwemJkMjE1alh6NzFUUkdjClJHWnY4dmRwcnZJR2dhQzRod0hh
            QWtjT3VrUVBYMi96S3BWeEpxNWdJOXcKLS0tIGhvNTFhTUVYZWhxYUQ4NE8zTWVz
            K3ZIZTBZbXdVVkdBRDBVVGE2cWFjM28KEUzqOrMCMKkHCBvFLNXRmlggrPB5275y
            8xsTjz8uUsUwk1h6j8HX2p8aAEOR4XMH36uAH4iK4LTCivP6ziUoqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:34:34Z"
    mac: ENC[AES256_GCM,data:tTy5iiBJZoRnP0Wl9bOmzJMJKm9/k/+vLA9w9yunS8ET4o+stoP/5WUuIGQyGLjfyt2Mg6Cr3giMPjoBOelAEPdtI7yLYeCqyhlrZ0p+YjnKAQeUwOcxa1FZOrrWWSFfJfZ5voFkNszM8RYS4usdoaHSK3ai165rV82kYG9W1sU=,iv:0tlddtswuNbO+uQiJ2wwoeUw4WjjGYwJYGIvamKMcEU=,tag:cZmUeHj1YVOps29T6nrf4Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
---
kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: homepage-secret
    namespace: homelab
stringData:
    HOMEPAGE_VAR_PLEX_URL: ENC[AES256_GCM,data:ApIsnB6H0DGOtkpwhQzOv7oaweKPBIBJ6A==,iv:IrFT4zHJLeP2bJxlMQJCVVlp55N5wcrZ/eSmPZMIMmw=,tag:D68R7XEpMCgddRxeOVujdw==,type:str]
    HOMEPAGE_VAR_PLEX_API_TOKEN: ENC[AES256_GCM,data:zd4T/4GEo3BURuVxANhmQ+geqfw=,iv:lFHrD6WtLv8x5ekt1+t6US7SG3l3wzFk/ZpDPLDeeH8=,tag:NtjkEn36Y1ydeefDsSMpAA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_URL: ENC[AES256_GCM,data:bdQWYWOvvUbG8jzt+R2tsyGntsWi4/ja,iv:OshV5Wt5x5UOgm23N3fCW+lRLUQF8PZHvGQfAoOHhe4=,tag:0PaOYEEWLuGcpp4TYbkpWA==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_USERNAME: ENC[AES256_GCM,data:twEK,iv:Yo58iRvOVXqrqOeKIEIl53r1MhIB6wSJrpqFtnoYnu8=,tag:FE/dp+JhWABdRki/e1AfQg==,type:str]
    HOMEPAGE_VAR_QBITTORRENT_PASSWORD: ENC[AES256_GCM,data:7vJNphM7hzD5,iv:lIpREJHOSXBij45OYWGKC2q9VcjrbiDZ4CRFKIC/ynk=,tag:eZDKkkCNCz8SYuDbdPbnNg==,type:str]
    HOMEPAGE_VAR_FILEBROWSER_URL: ENC[AES256_GCM,data:8Ck6+mYALtjmBl3GVjlqwc0tyK9bZznhW3RtEUFgGuRM,iv:pvOVeOdsDTVP4TOnjaAz+SoAEGgroNjbbpYOrUHSdL0=,tag:jarsZ+TytaRAjQQhO7VrLA==,type:str]
    HOMEPAGE_VAR_METUBE_URL: ENC[AES256_GCM,data:xIB0HVfgX1//fJcALTqcVsbuB6QiY5MmRQ==,iv:9kZVkAo5dehqcDeFuRj5N/K7D/v5z69SGVfeq+rNlJo=,tag:kVJMEZO0dbZoJjRsghX3uQ==,type:str]
    HOMEPAGE_VAR_LOST_URL: ENC[AES256_GCM,data:rk9Ux7d6OCv7xf62qOQQ4U+JN62AG2EwL3+LW4m2D4I=,iv:YpZUUtHeqOqW4XjkhV1IYp9g1KCpYKTCBVLae1ncUxM=,tag:FKqKZstMaVmusdZyEzuVvA==,type:str]
    HOMEPAGE_VAR_CINEMA_URL: ENC[AES256_GCM,data:AFMNx8YIPwmo5en+E3stmuKKNJ3PgsPj1AII3/pNIhi3ZA==,iv:qdDSj4Qudh5DTL3fwsisvKNpFmTwZjFTuZ/iPNHSckE=,tag:V97FAwWTgGzqGylZSRhvgQ==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_URL: ENC[AES256_GCM,data:0kqe35l9JALxJmT8wKNLP35Cmso29THzL52YJ9epvgS5OA==,iv:JrYNqov+iSrWgsnl1fXDqkwv/lDDU0bQ4LyEns7AIJA=,tag:WPEyMimP9ZRQSz4l1gp+fA==,type:str]
    HOMEPAGE_VAR_PHOTOPRISM_TOKEN: ENC[AES256_GCM,data:MhLc4+7jxJK+qzecrfPgSJjiZ+qx+lmogztx,iv:jEuZjGKxbf6/XNwSY9oJPEX7iWbWssmldoVqF/lTNFQ=,tag:T/8Dl1sPl3WJcINXxoic+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmYmJEbTN1Qk9kYTliQ1Zo
            NjRIS3hhckdMcTgwemJkMjE1alh6NzFUUkdjClJHWnY4dmRwcnZJR2dhQzRod0hh
            QWtjT3VrUVBYMi96S3BWeEpxNWdJOXcKLS0tIGhvNTFhTUVYZWhxYUQ4NE8zTWVz
            K3ZIZTBZbXdVVkdBRDBVVGE2cWFjM28KEUzqOrMCMKkHCBvFLNXRmlggrPB5275y
            8xsTjz8uUsUwk1h6j8HX2p8aAEOR4XMH36uAH4iK4LTCivP6ziUoqQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-26T19:34:34Z"
    mac: ENC[AES256_GCM,data:tTy5iiBJZoRnP0Wl9bOmzJMJKm9/k/+vLA9w9yunS8ET4o+stoP/5WUuIGQyGLjfyt2Mg6Cr3giMPjoBOelAEPdtI7yLYeCqyhlrZ0p+YjnKAQeUwOcxa1FZOrrWWSFfJfZ5voFkNszM8RYS4usdoaHSK3ai165rV82kYG9W1sU=,iv:0tlddtswuNbO+uQiJ2wwoeUw4WjjGYwJYGIvamKMcEU=,tag:cZmUeHj1YVOps29T6nrf4Q==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
