---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: homelab
spec:
  encryptedData:
    admin-password: AgAapqz1ObsPK1YdK2ok8YQeIaveqAOi3umqqQTccyqE3RkYCBDQL7Nu3DBqWU+7P/ewsc8FzIurVpvj/pVyVFYq8gj177ObiKdaqinfoKfH18Cq6wlHxLWoc0fazVEOsJ5s/uO1oexfBDbuH40ygqNKiilxEzB1y3BPb1xRy3XJrIkCYgsSD10Sm/33eHQTWo/0UvCNkez2k+2OZBqnU6micn7vK5tWISiv83c3KBoEKbMIxQxvdMEZcFhCNJDx6z1ab8+Upa8JSiO2uu2poOFC2hW5nl8sNoRKpXy1u3yQQPe2ubdqp6ho6iPYS+20CrRQJs0uc92Ta/SGsd864TOr/0FDj0Q6mGyI6NPV1SP9tvQkClyDujSRQmZHnULanZMxs/aAVV/fcxzWrnqdMl9UH8lCWZaDTz4/d7V74kLJa+ZxSZCxDLhKnTUWtquMJigFpfyqeZ3GkgYI8EvwL0INxWApy1Jbv8nv7th/7K1oH/WT23tS6+Z9bYPJ43p8Zha/KK5MubNfRAY9tYuDg/bjsPoxpiCRxfXZx+Av68h+wqq/YvcCLNVWsARIpvLnpZwEtIRXtZMUq76k5t9iFub976Lv3Bak2IjDTeSt0f0sn2RN6oSw85+w/CdQuZHzb1IgISLxQTrz15gEm7PjZ83RhqOtrVgz18FYCS49zS0GibHxXM8MYCqqylphTxtQ5BhmetBnaUaR/Gybwy/DaTg2
    admin-user: AgBJtHlOyYXklbq1Ng1apERgO01Z412j+zU23y7RBWOZeb3v+0i0RxFYN3qb1dG3UC7RRO1BzXmyDc7IP8EQdvpn+VXWliupo51UxsOhbelomfLlWVj8KBCod1DWXuLT8JosuG9uJkuJn/Y4Q3LQiA42Cwdmq4eOrHC0y03c4xTouw/FIFvDvLe/3cPYm6TzL5xuY9S9MOfZ05OUcpLBcr2+IaePOzGzxRfSiwRDYRAVbb5WtbMks5ICxpNqVuerLe383CaPcIrye4jqK/wY4wNcw6jzRg+fuy9UK5lvAiL/guXSThPLQ6vOPaDhZo80E7CGraNml4fPtxAm3XSjQYAb0MT9CSSCTiB3R7TUFpQH/Yho6giYvlLvqZJX+PjK5VMIrZfJHAeOebHDvOOyaSLCeGGTM2hYgbRb8bIr4UvDBfr6Z64cGkBpkB1R8/V/bWsJut4nINEMjjBRxFebVPEDtQNbnOhqBHKxN6p86D7tl6Pv1AKcVu3Z8zUJzO4clfQSlaDsk+m4IYoMvIgXMu7DB1cCK/qDGdPfvyy3ubpeytd2pej3L5b8x6oy+ys2OKjhH/VxnSBffwONdj6X0LpiUZTJKDGMeTejY/lKB7/L3qmEOXOKQcpx6kQkcqV0l7ArVTS3YyHa8dN2Ds6Ep96TJJScWHn2U38y6GmNIuWCirYJJpUaEBiHa35go0Xxr8Cg5uoFBQ==
  template:
    metadata:
      name: grafana-secret
      namespace: homelab
    type: Opaque
