---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-secret
  namespace: homelab
spec:
  encryptedData:
    admin-password: AgBZTiiSv2UMg37brP0aGxq5tWHpE4VZPl9SLJ1APqy9dxx/66DrItetkS241KxcIusulRoWP5pXI2Bnt4j7cYvHkWjVfOV6rbeJ9kA+amY7Nq0ftG/spGSEcJS2lDaJWR/g81be54AqTUx8o1EzsJMxIDghraqSXCmknwC+FCPlSTDQsWmAAXnB8Mfgo8WfNl5fCTaiY+hvpkaqbVBRAQeNVY3bZ5Zt68t0jejQS/hSYJA3kfcUOv/02sB9ezlm3dJyDYmJaF/6VELeDh6T1+TsaaCOuE+sZjw2DTWxpE67R4d+UzmKb3CYxYneJRND851QXig1xHs7mcxz486+TXV7/w/8tWzT1t6vqECTp2U19aKTdvR/jRlRzPtyHhSPjFDacA+rmC6dMAz9haRE0yoCgRdgIrNrvOj8WoXYZTsm1/X7lq7/fEoFobqlNhRQzbdGSGoi9JxKkyqbkIsJXl7CR1K6LqVeBKxy1oUbekrWVg49WcJ7oNLp/9iGNiCFPoheh5qXQDyhNyJSpAu4OMs9vzAnd30qRWXcYmq8mSFdt/1oj85aaUpCUT13Vy8gNJLa9L+gibkjv5dipk4mQUs+oM8O9l9bxGp7d6F8RojmZz3h/jLVUS91swWirU8mfQOxsCTXKq6wsAgkcRFGx/y9ei+L4Wkj/h5LWsXPpuPcgG0vR9aUm3DnIt9ulsBfG8BPi/anpGKeWrQwow==
    admin-user: AgB6bx/zyWrtzbJTsU0NQG0cxrMjZTbsnH1jhbkQREoMXo/kiBnom5lUDKc371giLcSMh5kkp8A38+fz8W8lK/2GUVFGlLnZoPAuWzRpVCFr6pDhDBJ/Z4YPvFoTYoox0SK2zeOVBsA/pQ5nIOIkt79VbaFj13A31/HQQiy5QVA9trgBXqLl6I4nBHHPEJkphr8e0W/g9RAb+FkR7EqFDLJ0Et5hQrQ+I6i4qq2voiPUORP2VIdapwGL55cvLTageFmeLqgY9kVpKOPnmDMEjRyPypxp5bmFitoOs2VldxApE5ETuI3l3ieNBRiULWxRaMGb8XvmcXXjxsV/jzh6K5kH9LnNX16lAbEnmGm7EFjm4JY1fWNar4bYY341tqlzAbVeu8SERheXTar2Cq3rZLf1BbtXsbuGn2NETEwRYYZ+tAGpt567KmWtrwjW6bMnlO5J+zSHih6lGbTjhHRbBNbPIPg9vE7vG8xpLrErWExsJpnpgcqFwu+Z0NzFloLBYWLJIs6URuIK9KEpcJq2MeNXDywa0/eSeI16ykST0reT5N4qX5LduH2knaXjnsOTHI94G6TndoKpxg4Q/xMYVnsTqkNUB6EnPX42rAkIxzW9hlJqtKgWpGdNiSUk1l3C2v6+6E3OekbLq3v+V7vLbgyJwXuNAaNBL1W8JkKxh16wQMq1W6pJuFs1SRjOejlLGDoQeWWSBA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-secret
      namespace: homelab
    type: Opaque
