---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qbitwebui-secret
  namespace: homelab
spec:
  encryptedData:
    encryption-key: AgB2xOyToG3I3lxXBWnlw3TS//3J/3EJbEOt+1MTBD4DiQiYlpX9EOqYc/rxFsDvcqKBT3jkLTYw5iE1Tz0xY8rGhHSobWk5w6e/FJYbgImmTfQ+lq7wCXHBuLRTch3YP6vcPl7gqynodiHKaULp0EdC5dIooqjshu0cv8Tgg1RD72p59cPOfiXNSn69iOgNzieE+L75zHhMH//tH8nN+aUFibzNVA4vqvd6WYwoeC9qUXcK+5dOAvRLC82NmV14sktdfnGNJcFG9fjolAVNY9+ptgQzU2XjREjIwUa+z2WNxU1n1vn7xEtU+aWeIZb5kXEYsq2417nXzwCiSG9xdnfWb2voWcF7t6so99p7aZxFOBEKKbVs+rFPsymLGppivsdZ+nP2Al3to3ag/+7qfjDssywpy3gSi6bwra/kSKZ9FibJP0YxLhrzJBkxyZKZWEMM4PKlJu3TyrlBk+9D1meWTdtlhMMpFtCG2BY6dhVapwsiS56xHW2ywY9k683Aogb4PL92uqzpHdkswcUW8+GaOrjoDsoFhrdF0rv8U83NI5ugRQVRnZC0A8FEwKnJeAjbUmLIPiUDGnLQDU7HC8QLYMNqrOOGMne1TjU5B32ENhF4A9IBsFYFuLmmN8ik9fPmIljik944B4yzF/iXk30ME+/7RScycbh0QI3KOiJGPGKHb831ZV8w8vGYlcC2QzA6E+FMIwgRWvDC9ZN3rO/UkuGMrtJntMnTOIlJqqDwygG9f1LVFMs505pUTFnturM=
  template:
    metadata:
      creationTimestamp: null
      name: qbitwebui-secret
      namespace: homelab
    type: Opaque
