apiVersion: v1
kind: Secret
metadata:
    name: photoprism-secret
    namespace: homelab
type: Opaque
data:
    admin-password: ENC[AES256_GCM,data:5uhpfyP3wWa5zyt7v845HQ22PiM=,iv:quq3yBzOdoLoLcVeCIsDXMeycRkzLR1VUrCElOmfa4M=,tag:9zZz2CMXJo+JWGRz3W6wMw==,type:str]
    database-password: ENC[AES256_GCM,data:SwPL+FGs8zwQHadR8O7Ls8bonJcJ5Swf2suSyMp4d5Y=,iv:wMUNx5Tb2AOudgq3vz3GWfAgp7kmXK4chbtqz44hCkw=,tag:gA4sjFiTVc6yzFm4WsUeZQ==,type:str]
    database-root-password: ENC[AES256_GCM,data:lsvU937GJduae4p1nK9bdV739Sbj0mdn,iv:8Ji7pFMByumGIfv4WTOgd9U9THwZoX729TuIyMoUo6A=,tag:gvj76n5NJQJd8DovXrE2yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fyxf44z7ztr6h06g65y7l2dvfemz73gfw3rcy657j22dhtlmnq3se0m8tn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArTlpCdlNwaFFCemR5RmYr
            UEN2alRIZERhWHFOUXM3YWNwaTlNVmRzTEg4CnJWV3J5cnUyNzV3SEV6Mkxja3Vx
            emlTb3ViM0VCYkltSDNiYUFDLy91YmMKLS0tIGc1Y1BqRWFxY3ZDTy9iRlFxeUlt
            eFh1QXMyMDZsOUxyQjlQcjZ0cDJ3VkkKHDyDd1T32XVbrOAB8yhJmV5yVYmlweV6
            gqFjToI3rofTTevgGXcYg38LFRPYXvUEthwp6CRSd/82He523zCzzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-24T19:53:15Z"
    mac: ENC[AES256_GCM,data:nKBCIPEregYqBACoGmKJzn9QoutYCkAo+Tpsb6WXuI7SiHtLPTnAiwKBcS7mnoeHN/IrfmrB+ycvtbr9JtWk+YgrIR4bBL9ENm//j7zeRVOH/ai5G7YiMW0oQYYbjXYjCHhncLByhlJBOu1BeHfu4FPh5RQ3HrcvFZoX7yHbqoI=,iv:lVxB8fOkhqfK5VVrPCrM7cR/HpwXyCwkmN1OA3Htopg=,tag:BTGWRcrP3cvGy5y6MIA9xw==,type:str]
    pgp: []
    encrypted_regex: ^(.*-(password|token|username|secret|apikey|api-key)|.*_(PASSWORD|TOKEN|USERNAME|SECRET|APIKEY|API_TOKEN|URL)|token|password|username|secret|apikey|api_key)$
    version: 3.8.1
